
---
- hosts: all
  connection: paramiko  # Workaround for windows hosts
  user: arma
  
  roles:
    - wine20
    - xvfb
    - steamcmd
    - git
    - unbuffer
    #- intercept
    #- intercept-example
    #- test-runner
    #- jenkins

  tasks:
    - copy:
        src: scripts
        dest: /home/arma
        force: no

    - file:
        path: /home/arma/scripts/updateArmaDevel.sh
        mode: 0755

    - file:
        path: /home/arma/scripts/login
        owner: arma
        group: arma

    - git:
        repo: https://github.com/overfl0/intercept-runtime-tests.git
        dest: /home/arma/armawindows/mpmissions/intercept-runtime-tests

    - git:
        repo: https://github.com/overfl0/intercept-runtime-tests.git
        dest: /home/arma/armalinux/mpmissions/intercept-runtime-tests
