
---
- hosts: all
  connection: paramiko  # Workaround for windows hosts
  become: yes  # Sudo
  user: arma
  
  roles:
    - wine20
    - xvfb
    - steamcmd
    #- intercept
    #- intercept-example
    #- test-runner
    #- jenkins

  tasks:
    - copy:
        src: scripts
        dest: /home/arma
        force: no

    - file:
        path: /home/arma/scripts/updateArmaDevel.sh
        mode: 0755

    - file:
        path: /home/arma/scripts/login
        owner: arma
        group: arma
